spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eventos-dominio
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql