spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pweb2-jwt
    username: postgres
    password: 1327
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql