spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/participante-ms
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql