server:
  port: 8080

spring:
  profiles:
    active: dev

app:
  autenticacaoPadrao:
    login: admin
    senha: 1234
    papel: ADMIN
    tipoAutenticacao: BANCO

security:
      authLoginUrl: /login
      tokenType: JWT
      issuer: ifpb
      audience: pweb2
      expiration: 3600000
      secret: s5v8y/A?D(G+KbPeShVmYq3t6w9z$C&E)H@McQfTjWnZr4u7x!A%D*G-JaNdRgUk
      ## Use: https://www.allkeysgenerator.com/ para gerar o segredo